# This is a basic workflow to help you get started with Actions

name: Python matrix test

# Controls when the workflow will run
on:
  - push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        py-version: [3.10, 3.11, 3.12]
        os: [ubuntu-latest, macos-14, windows-latest]
    runs-on: ${{ matrix.os }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        py-version: ${{ matrix.py-version }}
        
